### ISSUE TITLE
Node.js Foundation Technical Steering Committee (TSC) Meeting 2019-09-25

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#758]
## Time

**UTC Wed 25-Sep-2019 15:00 (03:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Wed 25-Sep-2019 08:00 (08:00 AM) |
| US / Mountain | Wed 25-Sep-2019 09:00 (09:00 AM) |
| US / Central  | Wed 25-Sep-2019 10:00 (10:00 AM) |
| US / Eastern  | Wed 25-Sep-2019 11:00 (11:00 AM) |
| London        | Wed 25-Sep-2019 16:00 (04:00 PM) |
| Amsterdam     | Wed 25-Sep-2019 17:00 (05:00 PM) |
| Moscow        | Wed 25-Sep-2019 18:00 (06:00 PM) |
| Chennai       | Wed 25-Sep-2019 20:30 (08:30 PM) |
| Hangzhou      | Wed 25-Sep-2019 23:00 (11:00 PM) |
| Tokyo         | Thu 26-Sep-2019 00:00 (12:00 AM) |
| Sydney        | Thu 26-Sep-2019 01:00 (01:00 AM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Technical%20Steering%20Committee%20(TSC)+Meeting+2019-09-25&iso=20190925T15
* or http://www.wolframalpha.com/input/?i=03PM+UTC%2C+Sep+25%2C+2019+in+local+time

## Links

* Minutes Google Doc: <https://docs.google.com/document/d/1AFnRJtDqx5hk_lDT9CzF1VAQHfln74djkI7TEVea4qw/edit>

## Agenda

* TSC representation on Moderation Team: https://github.com/nodejs/TSC/issues/757
* deps: update V8 to 7.8: https://github.com/nodejs/node/pull/29493
* src,lib: make ^C print a JS stack trace: https://github.com/nodejs/node/pull/29207
* build: ongoing list of actions for Python 3 compatibility: https://github.com/nodejs/node/issues/25789

## Invited

* Anna Henningsen @addaleax (TSC)
* Anatoli Papirovski @apapirovski (TSC)
* Beth Griggs @BethGriggs (TSC)
* Сковорода Никита Андреевич @ChALkeR (TSC)
* Colin Ihrig @cjihrig (TSC)
* Daniel Bevenius @danbev (TSC)
* Franziska Hinkelmann @fhinkel (TSC)
* Jeremiah Senkpiel @Fishrock123 (TSC)
* Gabriel Schulhof @gabrielschulhof (TSC)
* Gireesh Punathil @gireeshpunathil (TSC)
* James Snell @jasnell (TSC)
* Joyee Cheung @joyeecheung (TSC)
* Matteo Collina @mcollina (TSC)
* Michael Dawson @mhdawson (TSC)
* Myles Borins @MylesBorins (TSC)
* Sam Roberts @sam-github (TSC)
* Michaël Zasso @targos (TSC)
* Sakthipriyan Vairamani @thefourtheye (TSC)
* Tobias Nießen @tniessen (TSC)
* Rich Trott @Trott (TSC)

### Observers/Guests
* Christian Clauss @cclauss (guest participant)

## Notes

The agenda comes from issues labelled with `tsc-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

Zoom link: https://zoom.us/j/611357642
Regular password

## Public participation

We stream our conference call straight to YouTube so anyone can listen to it live, it should start playing at **https://www.youtube.com/c/nodejs+foundation/live** when we turn it on. There's usually a short cat-herding time at the start of the meeting and then occasionally we have some quick private business to attend to before we can start recording & streaming. So be patient and it should show up.

Many of us will be on IRC in #node-dev on Freenode if you'd like to interact, we have a Q/A session scheduled at the end of the meeting if you'd like us to discuss anything in particular. @nodejs/collaborators in particular if there's anything you need from the TSC that's not worth putting on as a separate agenda item, this is a good place for that.

---

**Invitees**

Please use the following emoji reactions in this post to indicate your
availability.

* :+1: - Attending
* :-1: - Not attending
* :confused: - Not sure yet

**Comment by sam-github** [comment]
I can attend, but with no agenda, will it occur?

**Comment by Trott** [comment]
> I can attend, but with no agenda, will it occur?

Looks like there was a problem (maybe temporary GitHub API failure?) with the meeting auto-generation. Here are the open issues and PRs in the org that have the `tsc-agenda` as of this writing:

* TSC representation on Moderation Team: https://github.com/nodejs/TSC/issues/757
* deps: update V8 to 7.8: https://github.com/nodejs/node/pull/29493
* src,lib: make ^C print a JS stack trace: https://github.com/nodejs/node/pull/29207
* build: ongoing list of actions for Python 3 compatibility: https://github.com/nodejs/node/issues/25789

**Comment by Trott** [comment]
(I've updated the issue description to include those four items in the agenda. I'll update the Google Doc too.)

**Comment by sam-github** [comment]
https://github.com/nodejs/security-wg/pull/579 could be discussed, too, though I don't know if it should go on the agenda before conversation has ocurred in the issue.

**Comment by mhdawson** [comment]
@Trott thanks for updating the issue. We do occasionally have that problem.  Tool could probably be improved...

**Comment by Fishrock123** [comment]
I have a bit of a cold and would rather get more sleep, so if this meeting happens, sorry!

**Comment by jasnell** [comment]
I'll be unable to attend today due to a schedule conflict. I'll weigh in on each issue on GitHub

**Comment by cclauss** [comment]
build: ongoing list of actions for Python 3 compatibility nodejs/node#25789
* [ ] tap2junit: v0.1.5 release (nodejs/tap2junit#12) to the Python Packaging Index [PyPI](https://pypi.org/project/tap2junit)
* [ ] node-gyp: release so that npm can pick it up https://github.com/nodejs/node-gyp/issues/1791#issuecomment-533715634
* [ ] re-vendor npm's gyp back into nodejs/node __/deps/npm/node_modules/node-gyp__
* [ ] Travis CI does not test ./configure --ninja test #29415   __*** help needed ***__
* [ ] node-gyp: Accept Python 3 by default (_semver-major_) nodejs/node-gyp#1844

**Comment by mcollina** [comment]
I won’t be able to attend today

**Comment by mhdawson** [comment]
PR for minutes: https://github.com/nodejs/TSC/pull/760
